---
- name: Load CPE list from CSV
  hosts: netbox
  gather_facts: no
#  tags: from_csv , never
  vars:
    csv_data_file: 'onboarding_ncr_asof83121.csv'
    
  tasks:

    - name: Setup base Data folder
      set_fact:
        base_data_folder: "{{ playbook_dir.split('playbooks') | first }}"

    - name: Read CSV File
      delegate_to: localhost
      read_csv:
        path: "{{ base_data_folder + 'net_data/' + csv_data_file }}"
      register: csv_file_data

- name: Onboard into Netbox
  hosts: netbox
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    tenant: 'PSC Demo'
  tasks:
    - name: Add nodes to netbox from CSV File
      ignore_errors: yes
#      tags: from_csv
      when: csv_file_data is defined     
      loop: "{{ csv_file_data.list }}"
      include_role:
        name: netbox/onboard_50_stores
        apply:
          tags: from_csv
      vars:
        netbox_url: "https://netbox.apolloglobal.net/"
        netbox_token: "e87e0916bdc7236b037746808c1c3b3da8fcba25"
        device_site: "{{ item['site_id'] }}"
        device_vendor: "ROUTER"
        device_model: "MODEL"
        site_status: "{{ item['sites_status'] }}"
        device_mgmt_ip: "{{ item['mgmt_ip'] }}"
        device_location: "{{ item['tag_location'] }}"
#        device_island: "{{ item['island_group'] }}"
        device_dctech: "{{ item['tag_dctech'] }}"
        device_role: "CPE"
        device_slug: "psc"
        device_tenant: "PSC"
        
