- name: Update Netbox Status for CPe
  hosts: all
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
   - name: Get CPE Status
     import_role:
        name: cpe/get_device_status

   - name: Update CPE Status into Netbox 
     import_role:
        name: netbox/set_device_status