---
- name: Update APT cache
  yum:
    update_cache: yes

- name: Install NGINX Packages
  yum:
    name: nginx

- name: Start NGINX Service
  service:
    name: nginx
    enabled: yes
    state: started

- name: Create ZTP Configs Folder
  file:
    path: /var/ztp_configs
    state: directory

- name: Open HTTP Ports on Firewalld
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: Disable SElinux
  selinux:
    state: disabled

- name: Reboot Machine
  reboot:
    reboot_timeout: 180
    test_command: whoami