---
- name: Adjust Network host in elastic
  become: yes
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    - { regex: 'network.host:', line: 'network.host: 0.0.0.0' }
    - { regex: 'discovery.type:', line: 'discovery.type: "single-node"' }


- name: Setup Xpack in Elasticsearch
  become: yes
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: "{{ item }}"
  loop:
    - 'xpack.license.self_generated.type: trial'
    - 'xpack.security.enabled: true'
    - 'xpack.monitoring.collection.enabled: true'


- name: Setup Xpack in Kibana
  become: yes
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: "{{ item }}"
  loop:
    - 'elasticsearch.username: elastic'
    - 'elasticsearch.password: changeme'

- name: Restart Elasticsearch
  become: yes
  service:
    name: elasticsearch
    state: restarted

- name: Restart Kibana and Logstash service
  become: yes
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - kibana
    - logstash