---
- name: Netbox -- Create Tenant for CPE
  ignore_errors: true
  netbox_tenant:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      name: "{{ device_tenant }} "
      slug: "{{ device_slug }}" 
    state: present
    validate_certs: false
  register: resulttenant
  until: resulttenant is not failed
  retries: 5
  async: 45
  poll: 0

- name: Netbox -- Create CPE Location
  netbox_site:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      name: "{{ device_site }}"
      custom_fields:
        Store Status: "{{ site_status }}"
      tenant: "{{ device_tenant | default(omit) }}"    
#      tags: 
#        - "{{ device_status | default(omit) }}"
#        - "{{ device_island | default(omit) }}"
#        - "{{ device_dctech | default(omit) }}"
#    state: present
    validate_certs: false
#  register: resultloc
#  until: resultloc is not failed
#  retries: 5

- name: Netbox -- Create manufacturer 
  netbox_manufacturer:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      name: "{{ device_vendor }}"
    state: present
    validate_certs: false
  register: resultman
  until: resultman is not failed
  retries: 5
  async: 45
  poll: 0

- name: Netbox --Create device role
  when: device_role is defined 
  netbox_device_role:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      name: "{{ device_role }}"
      color: FAB880
    state: present
    validate_certs: false
  register: resultrole
  until: resultrole is not failed
  retries: 5
  async: 45
  poll: 0

- name: Netbox --Create device type
  netbox_device_type:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      model: "{{ device_model }}"
      manufacturer: "{{ device_vendor }}"
    state: present
    validate_certs: false
  register: resulttype
  until: resulttype is not failed
  retries: 5
  async: 45
  poll: 0

- name: Netbox -- Create Device
  netbox_device:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      name: "{{ device_role + '-' + device_site }}"
      device_type: "{{ device_model }}"
      device_role: "{{ device_role | default(omit) }}"
      site: "{{ device_site }}"
      tenant: "{{ device_tenant | default(omit) }}"
      custom_fields:
        prom_labels: '{"__snmp_module__": "arista_sw"}'
    state: present
    validate_certs: false
  register: resultdev
  until: resultdev is not failed
  retries: 5
  async: 45
  poll: 0

