---
- name: Netbox -- Create Tenant for CPE
  ignore_errors: true
  netbox_tenant:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      name: "{{ device_tenant }} "
      slug: "{{ device_slug }}" 
    state: present
    validate_certs: false
  register: resulttenant
  until: resulttenant is not failed
  retries: 5

- name: Netbox -- Create CPE Location
  netbox_site:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      name: "{{ device_site }}"
      custom_fields:
        Store Status: "{{ site_status }}"
      tenant: "{{ device_tenant | default(omit) }}"    
#      tags: 
#        - "{{ device_status | default(omit) }}"
#        - "{{ device_island | default(omit) }}"
#        - "{{ device_dctech | default(omit) }}"
#    state: present
    validate_certs: false
#  register: resultloc
#  until: resultloc is not failed
#  retries: 5

- name: Netbox -- Create manufacturer 
  netbox_manufacturer:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      name: "{{ device_vendor }}"
    state: present
    validate_certs: false
  register: resultman
  until: resultman is not failed
  retries: 5
- name: Netbox --Create device role
  when: device_role is defined 
  netbox_device_role:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      name: "{{ device_role }}"
      color: FAB880
    state: present
    validate_certs: false
  register: resultrole
  until: resultrole is not failed
  retries: 5
- name: Netbox --Create device type
  netbox_device_type:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      model: "{{ device_model }}"
      manufacturer: "{{ device_vendor }}"
    state: present
    validate_certs: false
  register: resulttype
  until: resulttype is not failed
  retries: 5

- name: Netbox -- Create Device
  netbox_device:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      name: "{{ device_role + '-' + device_site }}"
      device_type: "{{ device_model }}"
      device_role: "{{ device_role | default(omit) }}"
      site: "{{ device_site }}"
      tenant: "{{ device_tenant | default(omit) }}"
      custom_fields:
        prom_labels: '{"__snmp_module__": "arista_sw"}'
    state: present
    validate_certs: false
  register: resultdev
  until: resultdev is not failed
  retries: 5
- name: Netbox -- Create  Dummy Mgmt Interface on a Device
  netbox_device_interface:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      device: "{{ device_role + '-' + device_site }}"
      name: "{{  device_dummy_mgmt_port }}"
      type: "Virtual"
      description: "Dummy Managment Port"
      mgmt_only: true
      mode: Access
      enabled: true
    state: present
    validate_certs: false
  register: resultcreatedummy
  until: resultcreatedummy is not failed
  retries: 5

#- name: Netbox -- get device id
#  shell: "curl -s https://netbox-sandbox.apolloglobal.net/api/dcim/devices/?name=CPE-ST-2345 -H 'Authorization: Token 9b5e317a31ef12015172f9af6a18c4624748ac38' | jq '.' | grep 'devices' | awk '{split($0,a,"/"); print a[7]}'"
#  delegate_to: 127.0.0.1
#  register: deviceid

#- debug:
#   msg: "{{deviceid}}"
  
#- name: Netbox -- remove old Mgmt IP Address on the Mgmt Interface
#  ignore_errors: true
#  netbox_ip_address:
#    netbox_url: "{{ netbox_url }}"
#    netbox_token: "{{ netbox_token }}"
#    data:
#      address: "{{ device_mgmt_ip }}"
#      tenant: "{{ device_tenant | default(omit) }}"
#      assigned_object:
#        name: "{{ device_dummy_mgmt_port }}"
#        device: "{{ device_role + '-' + device_site }}"
#    state: absent
#    validate_certs: false
#  register: resultrem
#  until: resultrem is not failed
#  retries: 5

- name: Netbox -- Attach Mgmt IP Address on the Mgmt Interface
  ignore_errors: true
  netbox_ip_address:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      address: "{{ device_mgmt_ip }}"
      tenant: "{{ device_tenant | default(omit) }}"
      assigned_object:
        name: "{{ device_dummy_mgmt_port }}"
        device: "{{ device_role + '-' + device_site }}"
    state: new
    validate_certs: false
  register: resultatt
  until: resultatt is not failed
  retries: 5

- name: Netbox -- Setup Managment IP on Device
  ignore_errors: true
  netbox_device:
    netbox_url: https://netbox-sandbox.apolloglobal.net/
    netbox_token: 6c3c25b8522dfc2bda9781e963ccc0f7a8edaf9d
    data:
      name: "{{device_role + '-' + device_site }}"
      site: "{{ device_site }}"
      primary_ip4: "{{ device_mgmt_ip | default(omit) }}"
    state: present
    validate_certs: false
  register: resultsett
  until: resultsett is not failed
  retries: 5

