- name: Netbox -- Update Device Status to Active
  when: connection_status
  netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ inventory_hostname }}"
      status: 'Active'
    state: present

- name: Netbox -- Update Device Status to Offline
  when: not connection_status
  netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ inventory_hostname }}"
      status: 'Offline'
    state: present