---
- name: Initialize Pre and Post Snapshots
  set_fact:
    pre: "{{ baseline_status.bgp_peers }}"
    post: "{{ bgp_peers }}"

- name: Initialize Interface Valdiation Errors
  set_fact:
    bgp_validation_errors: []

- name: Build Diff between Pre and Post
  set_fact:
    pre_state_validate: "{{ pre|dict2items|difference(post|dict2items) }}"
    post_state_validate: "{{ post|dict2items|difference(pre|dict2items) }}"

- name: Validate Against Pre State
  when: pre_state_validate | default([])  
  block:
    - name: Validate Ports have been removed
      set_fact:
        intf_validation_errors: "{{ intf_validation_errors + ['!! BGP Peer : ' + item.key  + ' Has been Removed' ]  }}"

      when: item.key not in post
      loop: "{{ pre_state_validate | default([]) }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Validate Port Status has Changed
      vars:
        pre_state: "{{ pre[item.key].state }}"
        post_state: "{{ post[item.key].state }}"
      set_fact:
        bgp_validation_errors: "{{ bgp_validation_errors + ['!! BGP Peer State Changed: ' + item.key + ' WAS: ' + pre_state + ' NOW: ' + post_state ] }}"

      when: 
        - item.key in post
        - pre[item.key].state != post[item.key].state

      loop: "{{ pre_state_validate | default([]) }}"
      loop_control:
        label: "{{ item.key }}"

- name: Add Interface Validation
  set_fact:
    validation_errors: "{{ validation_errors | combine({'bgp': bgp_validation_errors }) }}"
    
  when: bgp_validation_errors | length > 0