---
- name: Ensure Git is Installed
  yum:
    name: git
    state: present
    
- name: Check if awx Repo is already cloned
  become: no
  stat:
    path: "{{ awx_repo_dir }}"
  register: awx_repo_exists

- name: Clone AWX into configured directory.
  become: no
  git:
    repo: "{{ awx_repo }}"
    dest: "{{ awx_repo_dir }}"
    version: "{{ awx_version }}"
    force: true
    accept_hostkey: true
  when: not awx_repo_exists.stat.exists

- name: Ensure Required Folders are Created
  file:
    path: "{{ item }}"
    group: "{{ ansible_user }}"
    mode: '0775'
    state: directory
  loop:
   - "{{ postgres_data_dir }}"
   - "{{ docker_compose_dir }}"


- name: Install Required Python packages
  pip:
    name: "{{ item }}"
    state: present
  loop:
   - docker
   - docker-compose
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Run the Install AWX playbook
  tags: install
  become: no
  shell: "~/.local/bin/ansible-playbook -i inventory install.yml -e 'postgres_data_dir={{ postgres_data_dir }},
                                                          docker_compose_dir={{ docker_compose_dir }} admin_password=password'"

  # shell: "ansible-playbook -i inventory install.yml -e 'postgres_data_dir={{ postgres_data_dir }},
  #                                                         docker_compose_dir={{ docker_compose_dir }} admin_password=password'"
  args:
    chdir: "{{ awx_repo_dir }}/installer"
    creates: "{{ awx_repo_dir }}/awx_playbook_complete"
  vars:
    ansible_python_interpreter: /usr/bin/python3
